# Generated by Django 2.1.3 on 2018-12-05 01:57

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Message',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('sex', models.CharField(max_length=10)),
                ('year', models.CharField(max_length=10)),
                ('mess', models.CharField(max_length=150)),
                ('time', models.CharField(max_length=100)),
            ],
            options={
                'verbose_name': '匿名消息',
                'verbose_name_plural': '匿名消息',
            },
        ),
    ]
